storage:
  baseDir: "api"
  backupDirectory: "backup"
  compression: false
  fileExtensions: false
  csvDelimiter: " "

api:
  baseUrl: "https://forbes.com/forbesapi/"
  endpoints:
    list: "person/{URI}/0/position/true.json"
    profile: "person/{URI}.json"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    Accept: "application/json"
    Accept-Language: "en-US,en;q=0.9"
    Accept-Encoding: "gzip, deflate, br"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"
  rateLimiting:
    batch: 25
    timeout: 30000
    retries: 3
    requestDelay:
      max: 10
      min: 2
